[tool.poetry]
name = "github analytics (simpler)"
version = "0.0.0"
description = ""
authors = ["Aaron (\"AJ\") Steers"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
