# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Lint and Test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Set up Poetry
      uses: Gr1N/setup-poetry@v8
    - name: Poetry install
      run: poetry install
    - name: Lint with Ruff
      run: poetry run ruff --format github .

  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Set up Poetry
      uses: Gr1N/setup-poetry@v8
    - name: Poetry install
      run: poetry install
    - name: Test with pytest
      run: poetry run pytest
